name: Build and Push Docker Image

on:
  # 手动触发工作流
  workflow_dispatch: 
  repository_dispatch: 
    types: build_docker_image

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download simfang.ttf
        run: |
          # 下载 simfang.ttf 文件
          curl -L -o simfang.ttf https://gitee.com/ilooli/wechat-bot/raw/master/wechat-bot-implement/docker/simfang.ttf

      - name: Download wechat-bot.jar
        run: |
          # 下载 wechat-bot.jar 文件
          curl -L -o wechat-bot.jar https://github.com/maohais/wechat-bot-auto-docker/releases/latest/download/wechat-bot.jar

      - name: Set up QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile # Dockerfile 路径
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wechat-bot:latest
