name: BuildDockerfileImage

on:
  # 防止 Fork 乱用 actions 设置只能手动触发构建
  workflow_dispatch: 
  repository_dispatch:  
    types: build_docker_image

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download required files
        run: |
          # 使用 curl 下载文件，指定文件名
          curl -L -o simfang.ttf https://gitee.com/ilooli/wechat-bot/raw/master/wechat-bot-implement/docker/simfang.ttf
          curl -L -o wechat-bot.jar https://github.com/maohais/wechat-bot-auto-docker/releases/latest/download/wechat-bot.jar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile # Dockerfile 位置
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wechat-bot:latest
